// ChineseWords Pack 50: Animals
// Clean version for development - readable and LLM-friendly

export const pack50_animals = {
  meta: {
    wordpack: 50,
    packNumber: 50,
    title: "Animals",
    act: "Act III: Expansion",
    wordCount: 51
  },
  words: [
    ["狗", "gǒu", "dog", "perro", "chien", "cachorro", "chó", "สุนัข", "ឆ្កែ", "anjing", "anjing", "aso"],
    ["小狗", "xiǎogǒu", "puppy", "cachorro", "petit chien", "cachorrinho", "chó con", "ลูกสุนัข", "ឆ្កែតូច", "anak anjing", "anak anjing", "tuta"],
    ["一只狗", "yì zhī gǒu", "one dog", "un perro", "un chien", "um cachorro", "một con chó", "สุนัขหนึ่งตัว", "ឆ្កែមួយក្បាល", "seekor anjing", "seekor anjing", "isang aso"],
    ["猫", "māo", "cat", "gato", "chat", "gato", "mèo", "แมว", "ឆ្មា", "kucing", "kucing", "pusa"],
    ["小猫", "xiǎomāo", "kitten", "gatito", "petit chat", "gatinho", "mèo con", "ลูกแมว", "ឆ្មាតូច", "anak kucing", "anak kucing", "kuting"],
    ["一只猫", "yì zhī māo", "one cat", "un gato", "un chat", "um gato", "một con mèo", "แมวหนึ่งตัว", "ឆ្មាមួយក្បាល", "seekor kucing", "seekor kucing", "isang pusa"],
    ["鸟", "niǎo", "bird", "pájaro", "oiseau", "pássaro", "chim", "นก", "បក្សី", "burung", "burung", "ibon"],
    ["小鸟", "xiǎoniǎo", "little bird", "pajarito", "petit oiseau", "passarinho", "chim nhỏ", "นกตัวเล็ก", "បក្សីតូច", "burung kecil", "burung kecil", "maliit na ibon"],
    ["一只鸟", "yì zhī niǎo", "one bird", "un pájaro", "un oiseau", "um pássaro", "một con chim", "นกหนึ่งตัว", "បក្សីមួយក្បាល", "seekor burung", "seekor burung", "isang ibon"],
    ["鱼", "yú", "fish", "pez", "poisson", "peixe", "cá", "ปลา", "ត្រី", "ikan", "ikan", "isda"],
    ["小鱼", "xiǎoyú", "small fish", "pez pequeño", "petit poisson", "peixinho", "cá nhỏ", "ปลาตัวเล็ก", "ត្រីតូច", "ikan kecil", "ikan kecil", "maliit na isda"],
    ["一条鱼", "yì tiáo yú", "one fish", "un pez", "un poisson", "um peixe", "một con cá", "ปลาหนึ่งตัว", "ត្រីមួយក្បាល", "seekor ikan", "seekor ikan", "isang isda"],
    ["鸡", "jī", "chicken", "pollo", "poulet", "frango", "gà", "ไก่", "មាន់", "ayam", "ayam", "manok"],
    ["母鸡", "mǔjī", "hen", "gallina", "poule", "galinha", "gà mái", "แม่ไก่", "មាន់ញី", "ayam betina", "ayam betina", "inahin"],
    ["公鸡", "gōngjī", "rooster", "gallo", "coq", "galo", "gà trống", "ไก่ตัวผู้", "មាន់ឈ្មោល", "ayam jantan", "ayam jantan", "tandang"],
    ["鸭", "yā", "duck", "pato", "canard", "pato", "vịt", "เป็ด", "ទា", "bebek", "itik", "pato"],
    ["鸭子", "yāzi", "duck", "pato", "canard", "pato", "con vịt", "เป็ด", "ទា", "bebek", "itik", "pato"],
    ["一只鸭", "yì zhī yā", "one duck", "un pato", "un canard", "um pato", "một con vịt", "เป็ดหนึ่งตัว", "ទាមួយក្បាល", "seekor bebek", "seekor itik", "isang pato"],
    ["猪", "zhū", "pig", "cerdo", "cochon", "porco", "lợn", "หมู", "ជ្រូក", "babi", "babi", "baboy"],
    ["小猪", "xiǎozhū", "piglet", "cerdito", "petit cochon", "porquinho", "lợn con", "ลูกหมู", "ជ្រូកតូច", "anak babi", "anak babi", "biik"],
    ["一头猪", "yì tóu zhū", "one pig", "un cerdo", "un cochon", "um porco", "một con lợn", "หมูหนึ่งตัว", "ជ្រូកមួយក្បាល", "seekor babi", "seekor babi", "isang baboy"],
    ["牛", "niú", "cow", "vaca", "vache", "vaca", "bò", "วัว", "គោ", "sapi", "lembu", "baka"],
    ["黄牛", "huángniú", "ox", "buey", "bœuf", "boi", "bò vàng", "วัวควาย", "គោលឿង", "sapi", "lembu", "baka"],
    ["一头牛", "yì tóu niú", "one cow", "una vaca", "une vache", "uma vaca", "một con bò", "วัวหนึ่งตัว", "គោមួយក្បាល", "seekor sapi", "seekor lembu", "isang baka"],
    ["羊", "yáng", "sheep", "oveja", "mouton", "ovelha", "cừu", "แกะ", "ចៀម", "domba", "biri-biri", "tupa"],
    ["绵羊", "miányáng", "sheep", "oveja", "mouton", "ovelha", "cừu", "แกะ", "ចៀម", "domba", "biri-biri", "tupa"],
    ["山羊", "shānyáng", "goat", "cabra", "chèvre", "cabra", "dê", "แพะ", "ពពែ", "kambing", "kambing", "kambing"],
    ["马", "mǎ", "horse", "caballo", "cheval", "cavalo", "ngựa", "ม้า", "សេះ", "kuda", "kuda", "kabayo"],
    ["一匹马", "yì pǐ mǎ", "one horse", "un caballo", "un cheval", "um cavalo", "một con ngựa", "ม้าหนึ่งตัว", "សេះមួយក្បាល", "seekor kuda", "seekor kuda", "isang kabayo"],
    ["骑马", "qímǎ", "ride a horse", "montar a caballo", "monter à cheval", "andar a cavalo", "cưỡi ngựa", "ขี่ม้า", "ជិះសេះ", "naik kuda", "menunggang kuda", "sumakay ng kabayo"],
    ["兔子", "tùzi", "rabbit", "conejo", "lapin", "coelho", "thỏ", "กระต่าย", "ទន្សាយ", "kelinci", "arnab", "kuneho"],
    ["小兔", "xiǎotù", "little rabbit", "conejito", "petit lapin", "coelhinho", "thỏ con", "กระต่ายตัวเล็ก", "ទន្សាយតូច", "kelinci kecil", "arnab kecil", "maliit na kuneho"],
    ["一只兔子", "yì zhī tùzi", "one rabbit", "un conejo", "un lapin", "um coelho", "một con thỏ", "กระต่ายหนึ่งตัว", "ទន្សាយមួយក្បាល", "seekor kelinci", "seekor arnab", "isang kuneho"],
    ["老虎", "lǎohǔ", "tiger", "tigre", "tigre", "tigre", "hổ", "เสือ", "ខ្លា", "harimau", "harimau", "tigre"],
    ["大老虎", "dà lǎohǔ", "big tiger", "tigre grande", "grand tigre", "tigre grande", "con hổ lớn", "เสือใหญ่", "ខ្លាធំ", "harimau besar", "harimau besar", "malaking tigre"],
    ["一只老虎", "yì zhī lǎohǔ", "one tiger", "un tigre", "un tigre", "um tigre", "một con hổ", "เสือหนึ่งตัว", "ខ្លាមួយក្បាល", "seekor harimau", "seekor harimau", "isang tigre"],
    ["狮子", "shīzi", "lion", "león", "lion", "leão", "sư tử", "สิงโต", "តោ", "singa", "singa", "leon"],
    ["一头狮子", "yì tóu shīzi", "one lion", "un león", "un lion", "um leão", "một con sư tử", "สิงโตหนึ่งตัว", "តោមួយក្បាល", "seekor singa", "seekor singa", "isang leon"],
    ["大狮子", "dà shīzi", "big lion", "león grande", "grand lion", "leão grande", "sư tử lớn", "สิงโตใหญ่", "តោធំ", "singa besar", "singa besar", "malaking leon"],
    ["熊", "xióng", "bear", "oso", "ours", "urso", "gấu", "หมี", "ខ្លាឃ្មុំ", "beruang", "beruang", "oso"],
    ["大熊", "dàxióng", "big bear", "oso grande", "grand ours", "urso grande", "gấu lớn", "หมีใหญ่", "ខ្លាឃ្មុំធំ", "beruang besar", "beruang besar", "malaking oso"],
    ["一只熊", "yì zhī xióng", "one bear", "un oso", "un ours", "um urso", "một con gấu", "หมีหนึ่งตัว", "ខ្លាឃ្មុំមួយក្បាល", "seekor beruang", "seekor beruang", "isang oso"],
    ["熊猫", "xióngmāo", "panda", "panda", "panda", "panda", "gấu trúc", "หมีแพนด้า", "ខ្លាឃ្មុំប៉េនដា", "panda", "panda", "panda"],
    ["大熊猫", "dàxióngmāo", "giant panda", "panda gigante", "panda géant", "panda gigante", "gấu trúc lớn", "หมีแพนด้ายักษ์", "ខ្លាឃ្មុំប៉េនដាយក្ស", "panda raksasa", "panda gergasi", "malaking panda"],
    ["国宝熊猫", "guóbǎo xióngmāo", "national treasure panda", "panda tesoro nacional", "panda trésor national", "panda tesouro nacional", "gấu trúc quốc bảo", "หมีแพนด้าสมบัติของชาติ", "ខ្លាឃ្មុំប៉េនដាជាតិ", "panda harta nasional", "panda khazanah negara", "panda na pambansang yaman"],
    ["蛇", "shé", "snake", "serpiente", "serpent", "cobra", "rắn", "งู", "ពស់", "ular", "ular", "ahas"],
    ["一条蛇", "yì tiáo shé", "one snake", "una serpiente", "un serpent", "uma cobra", "một con rắn", "งูหนึ่งตัว", "ពស់មួយក្បាល", "seekor ular", "seekor ular", "isang ahas"],
    ["毒蛇", "dúshé", "venomous snake", "serpiente venenosa", "serpent venimeux", "cobra venenosa", "rắn độc", "งูพิษ", "ពស់ពិស", "ular berbisa", "ular berbisa", "makamandag na ahas"],
    ["昆虫", "kūnchóng", "insect", "insecto", "insecte", "inseto", "côn trùng", "แมลง", "សត្វល្អិត", "serangga", "serangga", "insekto"],
    ["小虫", "xiǎochóng", "small insect", "insecto pequeño", "petit insecte", "inseto pequeno", "sâu bọ", "แมลงเล็ก", "សត្វល្អិតតូច", "serangga kecil", "serangga kecil", "maliit na insekto"],
    ["虫子", "chóngzi", "bug", "bicho", "insecte", "inseto", "con trùng", "แมลง", "សត្វល្អិត", "serangga", "serangga", "insekto"]
  ]
};
